name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  BUILD_ARCHITECTURE: x86

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: ${{ env.BUILD_ARCHITECTURE }}

    - name: Build Solution
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:Platform=${{ env.BUILD_ARCHITECTURE }} ${{ env.SOLUTION_FILE_PATH }}

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CoHModSDK
        path: |
            ${{ env.SOLUTION_FILE_PATH }}/_build/ModSDK_Core/bin/${{ env.BUILD_CONFIGURATION }}/${{ env.BUILD_ARCHITECTURE }}
            ${{ env.SOLUTION_FILE_PATH }}/_build/ModSDK_Loader/bin/${{ env.BUILD_CONFIGURATION }}/${{ env.BUILD_ARCHITECTURE }}
        retention-days: 1
