name: Create Release

on:
  workflow_dispatch:
    inputs:
      build-ver:
        description: Build version
        required: true
        default: v0.0.0

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: CoHModSDK
        path: artifact

    - name: Create Release Zips
      run: |
        mkdir -p CoHModSDK_Core
        mkdir -p CoHModSDK_Loader
        cp -a artifact/CoHModSDK.lib CoHModSDK_Core/
        cp -a artifact/CoHModSDKLoader.dll CoHModSDK_Loader/
        cd CoHModSDK_Core
        zip -r ../CoHModSDK_Core-${{ github.event.inputs.build-ver }}.zip .
        cd ../CoHModSDK_Loader
        zip -r ../CoHModSDK_Loader-${{ github.event.inputs.build-ver }}.zip .
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.build-ver }}
        name: ${{ github.event.inputs.build-ver }}
        files: |
          CoHModSDK_Core-${{ github.event.inputs.build-ver }}.zip
          CoHModSDK_Loader-${{ github.event.inputs.build-ver }}.zip
        draft: false
        prerelease: false
        make_latest: true
